name: My first workflow
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.13.0'
            - run: node -v
